//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `solana_core_multisig` program ID.
  pub const SOLANA_CORE_MULTISIG_ID: Pubkey = pubkey!("C9h86YyYMpKViSzRpE7XUPrRVRypu5WTSitJ9n8czcZh");

