/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@metaplex-foundation/umi';
import {
  getSolanaCoreMultisigErrorFromCode,
  getSolanaCoreMultisigErrorFromName,
} from '../errors';

export const SOLANA_CORE_MULTISIG_PROGRAM_ID =
  'C9h86YyYMpKViSzRpE7XUPrRVRypu5WTSitJ9n8czcZh' as PublicKey<'C9h86YyYMpKViSzRpE7XUPrRVRypu5WTSitJ9n8czcZh'>;

export function createSolanaCoreMultisigProgram(): Program {
  return {
    name: 'solanaCoreMultisig',
    publicKey: SOLANA_CORE_MULTISIG_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getSolanaCoreMultisigErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getSolanaCoreMultisigErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getSolanaCoreMultisigProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('solanaCoreMultisig', clusterFilter);
}

export function getSolanaCoreMultisigProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey(
    'solanaCoreMultisig',
    SOLANA_CORE_MULTISIG_PROGRAM_ID,
    clusterFilter
  );
}
