/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CANCEL_TX_DISCRIMINATOR = new Uint8Array([
  235, 85, 151, 12, 219, 197, 50, 18,
]);

export function getCancelTxDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CANCEL_TX_DISCRIMINATOR);
}

export type CancelTxInstruction<
  TProgram extends string = typeof SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS,
  TAccountMultisig extends string | IAccountMeta<string> = string,
  TAccountTransaction extends string | IAccountMeta<string> = string,
  TAccountProposer extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransaction extends string
        ? WritableAccount<TAccountTransaction>
        : TAccountTransaction,
      TAccountProposer extends string
        ? WritableSignerAccount<TAccountProposer> &
            IAccountSignerMeta<TAccountProposer>
        : TAccountProposer,
      ...TRemainingAccounts,
    ]
  >;

export type CancelTxInstructionData = { discriminator: ReadonlyUint8Array };

export type CancelTxInstructionDataArgs = {};

export function getCancelTxInstructionDataEncoder(): Encoder<CancelTxInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CANCEL_TX_DISCRIMINATOR }),
  );
}

export function getCancelTxInstructionDataDecoder(): Decoder<CancelTxInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCancelTxInstructionDataCodec(): Codec<
  CancelTxInstructionDataArgs,
  CancelTxInstructionData
> {
  return combineCodec(
    getCancelTxInstructionDataEncoder(),
    getCancelTxInstructionDataDecoder(),
  );
}

export type CancelTxInput<
  TAccountMultisig extends string = string,
  TAccountTransaction extends string = string,
  TAccountProposer extends string = string,
> = {
  multisig: Address<TAccountMultisig>;
  transaction: Address<TAccountTransaction>;
  proposer: TransactionSigner<TAccountProposer>;
};

export function getCancelTxInstruction<
  TAccountMultisig extends string,
  TAccountTransaction extends string,
  TAccountProposer extends string,
  TProgramAddress extends Address = typeof SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS,
>(
  input: CancelTxInput<TAccountMultisig, TAccountTransaction, TAccountProposer>,
  config?: { programAddress?: TProgramAddress },
): CancelTxInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountTransaction,
  TAccountProposer
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: true },
    proposer: { value: input.proposer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.proposer),
    ],
    programAddress,
    data: getCancelTxInstructionDataEncoder().encode({}),
  } as CancelTxInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountTransaction,
    TAccountProposer
  >;

  return instruction;
}

export type ParsedCancelTxInstruction<
  TProgram extends string = typeof SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    multisig: TAccountMetas[0];
    transaction: TAccountMetas[1];
    proposer: TAccountMetas[2];
  };
  data: CancelTxInstructionData;
};

export function parseCancelTxInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedCancelTxInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      transaction: getNextAccount(),
      proposer: getNextAccount(),
    },
    data: getCancelTxInstructionDataDecoder().decode(instruction.data),
  };
}
