/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const EXECUTE_TX_DISCRIMINATOR = new Uint8Array([
  249, 17, 145, 23, 12, 252, 17, 41,
]);

export function getExecuteTxDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(EXECUTE_TX_DISCRIMINATOR);
}

export type ExecuteTxInstruction<
  TProgram extends string = typeof SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS,
  TAccountMultisig extends string | IAccountMeta<string> = string,
  TAccountMultisigSigner extends string | IAccountMeta<string> = string,
  TAccountTransaction extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? WritableSignerAccount<TAccountMultisig> &
            IAccountSignerMeta<TAccountMultisig>
        : TAccountMultisig,
      TAccountMultisigSigner extends string
        ? ReadonlyAccount<TAccountMultisigSigner>
        : TAccountMultisigSigner,
      TAccountTransaction extends string
        ? WritableAccount<TAccountTransaction>
        : TAccountTransaction,
      ...TRemainingAccounts,
    ]
  >;

export type ExecuteTxInstructionData = { discriminator: ReadonlyUint8Array };

export type ExecuteTxInstructionDataArgs = {};

export function getExecuteTxInstructionDataEncoder(): Encoder<ExecuteTxInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: EXECUTE_TX_DISCRIMINATOR }),
  );
}

export function getExecuteTxInstructionDataDecoder(): Decoder<ExecuteTxInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getExecuteTxInstructionDataCodec(): Codec<
  ExecuteTxInstructionDataArgs,
  ExecuteTxInstructionData
> {
  return combineCodec(
    getExecuteTxInstructionDataEncoder(),
    getExecuteTxInstructionDataDecoder(),
  );
}

export type ExecuteTxAsyncInput<
  TAccountMultisig extends string = string,
  TAccountMultisigSigner extends string = string,
  TAccountTransaction extends string = string,
> = {
  multisig: TransactionSigner<TAccountMultisig>;
  multisigSigner?: Address<TAccountMultisigSigner>;
  transaction: Address<TAccountTransaction>;
};

export async function getExecuteTxInstructionAsync<
  TAccountMultisig extends string,
  TAccountMultisigSigner extends string,
  TAccountTransaction extends string,
  TProgramAddress extends Address = typeof SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS,
>(
  input: ExecuteTxAsyncInput<
    TAccountMultisig,
    TAccountMultisigSigner,
    TAccountTransaction
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ExecuteTxInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountMultisigSigner,
    TAccountTransaction
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: true },
    multisigSigner: { value: input.multisigSigner ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.multisigSigner.value) {
    accounts.multisigSigner.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 117, 108, 116, 105, 115, 105, 103]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.multisig.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.multisigSigner),
      getAccountMeta(accounts.transaction),
    ],
    programAddress,
    data: getExecuteTxInstructionDataEncoder().encode({}),
  } as ExecuteTxInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountMultisigSigner,
    TAccountTransaction
  >;

  return instruction;
}

export type ExecuteTxInput<
  TAccountMultisig extends string = string,
  TAccountMultisigSigner extends string = string,
  TAccountTransaction extends string = string,
> = {
  multisig: TransactionSigner<TAccountMultisig>;
  multisigSigner: Address<TAccountMultisigSigner>;
  transaction: Address<TAccountTransaction>;
};

export function getExecuteTxInstruction<
  TAccountMultisig extends string,
  TAccountMultisigSigner extends string,
  TAccountTransaction extends string,
  TProgramAddress extends Address = typeof SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS,
>(
  input: ExecuteTxInput<
    TAccountMultisig,
    TAccountMultisigSigner,
    TAccountTransaction
  >,
  config?: { programAddress?: TProgramAddress },
): ExecuteTxInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountMultisigSigner,
  TAccountTransaction
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: true },
    multisigSigner: { value: input.multisigSigner ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.multisigSigner),
      getAccountMeta(accounts.transaction),
    ],
    programAddress,
    data: getExecuteTxInstructionDataEncoder().encode({}),
  } as ExecuteTxInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountMultisigSigner,
    TAccountTransaction
  >;

  return instruction;
}

export type ParsedExecuteTxInstruction<
  TProgram extends string = typeof SOLANA_CORE_MULTISIG_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    multisig: TAccountMetas[0];
    multisigSigner: TAccountMetas[1];
    transaction: TAccountMetas[2];
  };
  data: ExecuteTxInstructionData;
};

export function parseExecuteTxInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedExecuteTxInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      multisigSigner: getNextAccount(),
      transaction: getNextAccount(),
    },
    data: getExecuteTxInstructionDataDecoder().decode(instruction.data),
  };
}
