# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "multisig" 
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "npm"
    directory: "./blinks" 
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "npm"
    directory: "./client/js" 
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "npm"
    directory: "./client" 
    schedule:
      interval: "daily"
