//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
#[derive(Debug)]
pub struct InitializeMultisig {
      
              
          pub multisig: solana_pubkey::Pubkey,
      }

impl InitializeMultisig {
  pub fn instruction(&self, args: InitializeMultisigInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: InitializeMultisigInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(1+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.multisig,
            true
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&InitializeMultisigInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::SOLANA_CORE_MULTISIG_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitializeMultisigInstructionData {
            discriminator: [u8; 8],
                        }

impl InitializeMultisigInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [220, 130, 117, 21, 27, 227, 78, 213],
                                                            }
  }
}

impl Default for InitializeMultisigInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitializeMultisigInstructionArgs {
                  pub owners: Vec<Pubkey>,
                pub threshold: u64,
                pub bump: u8,
      }


/// Instruction builder for `InitializeMultisig`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` multisig
#[derive(Clone, Debug, Default)]
pub struct InitializeMultisigBuilder {
            multisig: Option<solana_pubkey::Pubkey>,
                        owners: Option<Vec<Pubkey>>,
                threshold: Option<u64>,
                bump: Option<u8>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitializeMultisigBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn multisig(&mut self, multisig: solana_pubkey::Pubkey) -> &mut Self {
                        self.multisig = Some(multisig);
                    self
    }
                    #[inline(always)]
      pub fn owners(&mut self, owners: Vec<Pubkey>) -> &mut Self {
        self.owners = Some(owners);
        self
      }
                #[inline(always)]
      pub fn threshold(&mut self, threshold: u64) -> &mut Self {
        self.threshold = Some(threshold);
        self
      }
                #[inline(always)]
      pub fn bump(&mut self, bump: u8) -> &mut Self {
        self.bump = Some(bump);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = InitializeMultisig {
                              multisig: self.multisig.expect("multisig is not set"),
                      };
          let args = InitializeMultisigInstructionArgs {
                                                              owners: self.owners.clone().expect("owners is not set"),
                                                                  threshold: self.threshold.clone().expect("threshold is not set"),
                                                                  bump: self.bump.clone().expect("bump is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `initialize_multisig` CPI accounts.
  pub struct InitializeMultisigCpiAccounts<'a, 'b> {
          
                    
              pub multisig: &'b solana_account_info::AccountInfo<'a>,
            }

/// `initialize_multisig` CPI instruction.
pub struct InitializeMultisigCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub multisig: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: InitializeMultisigInstructionArgs,
  }

impl<'a, 'b> InitializeMultisigCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: InitializeMultisigCpiAccounts<'a, 'b>,
              args: InitializeMultisigInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              multisig: accounts.multisig,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(1+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.multisig.key,
            true
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&InitializeMultisigInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::SOLANA_CORE_MULTISIG_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(2 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.multisig.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `InitializeMultisig` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` multisig
#[derive(Clone, Debug)]
pub struct InitializeMultisigCpiBuilder<'a, 'b> {
  instruction: Box<InitializeMultisigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitializeMultisigCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(InitializeMultisigCpiBuilderInstruction {
      __program: program,
              multisig: None,
                                            owners: None,
                                threshold: None,
                                bump: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn multisig(&mut self, multisig: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.multisig = Some(multisig);
                    self
    }
                    #[inline(always)]
      pub fn owners(&mut self, owners: Vec<Pubkey>) -> &mut Self {
        self.instruction.owners = Some(owners);
        self
      }
                #[inline(always)]
      pub fn threshold(&mut self, threshold: u64) -> &mut Self {
        self.instruction.threshold = Some(threshold);
        self
      }
                #[inline(always)]
      pub fn bump(&mut self, bump: u8) -> &mut Self {
        self.instruction.bump = Some(bump);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_entrypoint::ProgramResult {
          let args = InitializeMultisigInstructionArgs {
                                                              owners: self.instruction.owners.clone().expect("owners is not set"),
                                                                  threshold: self.instruction.threshold.clone().expect("threshold is not set"),
                                                                  bump: self.instruction.bump.clone().expect("bump is not set"),
                                    };
        let instruction = InitializeMultisigCpi {
        __program: self.instruction.__program,
                  
          multisig: self.instruction.multisig.expect("multisig is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct InitializeMultisigCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            multisig: Option<&'b solana_account_info::AccountInfo<'a>>,
                        owners: Option<Vec<Pubkey>>,
                threshold: Option<u64>,
                bump: Option<u8>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

