//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#approve;
  pub(crate) mod r#cancel_tx;
  pub(crate) mod r#create_tx;
  pub(crate) mod r#edit_tx;
  pub(crate) mod r#execute_tx;
  pub(crate) mod r#initialize_multisig;
  pub(crate) mod r#revoke_approval;

  pub use self::r#approve::*;
  pub use self::r#cancel_tx::*;
  pub use self::r#create_tx::*;
  pub use self::r#edit_tx::*;
  pub use self::r#execute_tx::*;
  pub use self::r#initialize_multisig::*;
  pub use self::r#revoke_approval::*;

