[toolchain]
package_manager = "npm"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
multisig = "AwhGP9QqsN2JAaS2XyYo2PeC2EAvkCExYLd5Mfuq1GaQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-mollusk = "cargo test-sbf"
test = "npm ts-mocha -p ./tsconfig.json -t 1000000 tests/anchor.test.ts"

