/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type TransactionRevoked = {
  multisig: Address;
  transaction: Address;
  proposer: Address;
};

export type TransactionRevokedArgs = TransactionRevoked;

export function getTransactionRevokedEncoder(): Encoder<TransactionRevokedArgs> {
  return getStructEncoder([
    ["multisig", getAddressEncoder()],
    ["transaction", getAddressEncoder()],
    ["proposer", getAddressEncoder()],
  ]);
}

export function getTransactionRevokedDecoder(): Decoder<TransactionRevoked> {
  return getStructDecoder([
    ["multisig", getAddressDecoder()],
    ["transaction", getAddressDecoder()],
    ["proposer", getAddressDecoder()],
  ]);
}

export function getTransactionRevokedCodec(): Codec<
  TransactionRevokedArgs,
  TransactionRevoked
> {
  return combineCodec(
    getTransactionRevokedEncoder(),
    getTransactionRevokedDecoder(),
  );
}
