/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type TransactionAccount = {
  pubkey: Address;
  isSigner: boolean;
  isWritable: boolean;
};

export type TransactionAccountArgs = TransactionAccount;

export function getTransactionAccountEncoder(): Encoder<TransactionAccountArgs> {
  return getStructEncoder([
    ["pubkey", getAddressEncoder()],
    ["isSigner", getBooleanEncoder()],
    ["isWritable", getBooleanEncoder()],
  ]);
}

export function getTransactionAccountDecoder(): Decoder<TransactionAccount> {
  return getStructDecoder([
    ["pubkey", getAddressDecoder()],
    ["isSigner", getBooleanDecoder()],
    ["isWritable", getBooleanDecoder()],
  ]);
}

export function getTransactionAccountCodec(): Codec<
  TransactionAccountArgs,
  TransactionAccount
> {
  return combineCodec(
    getTransactionAccountEncoder(),
    getTransactionAccountDecoder(),
  );
}
