/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type TransactionCancelled = {
  multisig: Address;
  transaction: Address;
  programId: Address;
};

export type TransactionCancelledArgs = TransactionCancelled;

export function getTransactionCancelledEncoder(): Encoder<TransactionCancelledArgs> {
  return getStructEncoder([
    ["multisig", getAddressEncoder()],
    ["transaction", getAddressEncoder()],
    ["programId", getAddressEncoder()],
  ]);
}

export function getTransactionCancelledDecoder(): Decoder<TransactionCancelled> {
  return getStructDecoder([
    ["multisig", getAddressDecoder()],
    ["transaction", getAddressDecoder()],
    ["programId", getAddressDecoder()],
  ]);
}

export function getTransactionCancelledCodec(): Codec<
  TransactionCancelledArgs,
  TransactionCancelled
> {
  return combineCodec(
    getTransactionCancelledEncoder(),
    getTransactionCancelledDecoder(),
  );
}
