/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type TransactionApproved = {
  multisig: Address;
  transaction: Address;
  programId: Address;
  approver: Address;
};

export type TransactionApprovedArgs = TransactionApproved;

export function getTransactionApprovedEncoder(): Encoder<TransactionApprovedArgs> {
  return getStructEncoder([
    ["multisig", getAddressEncoder()],
    ["transaction", getAddressEncoder()],
    ["programId", getAddressEncoder()],
    ["approver", getAddressEncoder()],
  ]);
}

export function getTransactionApprovedDecoder(): Decoder<TransactionApproved> {
  return getStructDecoder([
    ["multisig", getAddressDecoder()],
    ["transaction", getAddressDecoder()],
    ["programId", getAddressDecoder()],
    ["approver", getAddressDecoder()],
  ]);
}

export function getTransactionApprovedCodec(): Codec<
  TransactionApprovedArgs,
  TransactionApproved
> {
  return combineCodec(
    getTransactionApprovedEncoder(),
    getTransactionApprovedDecoder(),
  );
}
