/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getTransactionAccountDecoder,
  getTransactionAccountEncoder,
  type TransactionAccount,
  type TransactionAccountArgs,
} from ".";

export type TransactionEdited = {
  multisig: Address;
  transaction: Address;
  programId: Address;
  accounts: Array<TransactionAccount>;
  data: ReadonlyUint8Array;
  signers: Array<boolean>;
};

export type TransactionEditedArgs = {
  multisig: Address;
  transaction: Address;
  programId: Address;
  accounts: Array<TransactionAccountArgs>;
  data: ReadonlyUint8Array;
  signers: Array<boolean>;
};

export function getTransactionEditedEncoder(): Encoder<TransactionEditedArgs> {
  return getStructEncoder([
    ["multisig", getAddressEncoder()],
    ["transaction", getAddressEncoder()],
    ["programId", getAddressEncoder()],
    ["accounts", getArrayEncoder(getTransactionAccountEncoder())],
    ["data", addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
    ["signers", getArrayEncoder(getBooleanEncoder())],
  ]);
}

export function getTransactionEditedDecoder(): Decoder<TransactionEdited> {
  return getStructDecoder([
    ["multisig", getAddressDecoder()],
    ["transaction", getAddressDecoder()],
    ["programId", getAddressDecoder()],
    ["accounts", getArrayDecoder(getTransactionAccountDecoder())],
    ["data", addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
    ["signers", getArrayDecoder(getBooleanDecoder())],
  ]);
}

export function getTransactionEditedCodec(): Codec<
  TransactionEditedArgs,
  TransactionEdited
> {
  return combineCodec(
    getTransactionEditedEncoder(),
    getTransactionEditedDecoder(),
  );
}
