//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

      pub(crate) mod solana_core_multisig;
  
      pub use self::solana_core_multisig::SolanaCoreMultisigError;
  
