/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  bytes,
  mapSerializer,
  publicKey as publicKeySerializer,
  struct,
  u32,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';
import {
  TransactionAccount,
  TransactionAccountArgs,
  getTransactionAccountSerializer,
} from '../types';

// Accounts.
export type CreateTxInstructionAccounts = {
  multisig: PublicKey | Pda;
  transaction: PublicKey | Pda;
  proposer: Signer;
};

// Data.
export type CreateTxInstructionData = {
  discriminator: Uint8Array;
  pid: PublicKey;
  data: Uint8Array;
  accs: Array<TransactionAccount>;
};

export type CreateTxInstructionDataArgs = {
  pid: PublicKey;
  data: Uint8Array;
  accs: Array<TransactionAccountArgs>;
};

export function getCreateTxInstructionDataSerializer(): Serializer<
  CreateTxInstructionDataArgs,
  CreateTxInstructionData
> {
  return mapSerializer<
    CreateTxInstructionDataArgs,
    any,
    CreateTxInstructionData
  >(
    struct<CreateTxInstructionData>(
      [
        ['discriminator', bytes({ size: 8 })],
        ['pid', publicKeySerializer()],
        ['data', bytes({ size: u32() })],
        ['accs', array(getTransactionAccountSerializer())],
      ],
      { description: 'CreateTxInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([97, 223, 80, 153, 55, 13, 155, 12]),
    })
  ) as Serializer<CreateTxInstructionDataArgs, CreateTxInstructionData>;
}

// Args.
export type CreateTxInstructionArgs = CreateTxInstructionDataArgs;

// Instruction.
export function createTx(
  context: Pick<Context, 'programs'>,
  input: CreateTxInstructionAccounts & CreateTxInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaCoreMultisig',
    'C9h86YyYMpKViSzRpE7XUPrRVRypu5WTSitJ9n8czcZh'
  );

  // Accounts.
  const resolvedAccounts = {
    multisig: {
      index: 0,
      isWritable: true as boolean,
      value: input.multisig ?? null,
    },
    transaction: {
      index: 1,
      isWritable: true as boolean,
      value: input.transaction ?? null,
    },
    proposer: {
      index: 2,
      isWritable: false as boolean,
      value: input.proposer ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: CreateTxInstructionArgs = { ...input };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getCreateTxInstructionDataSerializer().serialize(
    resolvedArgs as CreateTxInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
