/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type RevokeApprovalInstructionAccounts = {
  multisig: PublicKey | Pda;
  transaction: PublicKey | Pda;
  proposer: Signer;
};

// Data.
export type RevokeApprovalInstructionData = { discriminator: Uint8Array };

export type RevokeApprovalInstructionDataArgs = {};

export function getRevokeApprovalInstructionDataSerializer(): Serializer<
  RevokeApprovalInstructionDataArgs,
  RevokeApprovalInstructionData
> {
  return mapSerializer<
    RevokeApprovalInstructionDataArgs,
    any,
    RevokeApprovalInstructionData
  >(
    struct<RevokeApprovalInstructionData>(
      [['discriminator', bytes({ size: 8 })]],
      { description: 'RevokeApprovalInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([44, 51, 184, 108, 182, 202, 20, 53]),
    })
  ) as Serializer<
    RevokeApprovalInstructionDataArgs,
    RevokeApprovalInstructionData
  >;
}

// Instruction.
export function revokeApproval(
  context: Pick<Context, 'programs'>,
  input: RevokeApprovalInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaCoreMultisig',
    'C9h86YyYMpKViSzRpE7XUPrRVRypu5WTSitJ9n8czcZh'
  );

  // Accounts.
  const resolvedAccounts = {
    multisig: {
      index: 0,
      isWritable: true as boolean,
      value: input.multisig ?? null,
    },
    transaction: {
      index: 1,
      isWritable: true as boolean,
      value: input.transaction ?? null,
    },
    proposer: {
      index: 2,
      isWritable: false as boolean,
      value: input.proposer ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getRevokeApprovalInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
