/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  publicKey as publicKeySerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';

export type AuthEvent = { multisig: PublicKey; programId: PublicKey };

export type AuthEventArgs = AuthEvent;

export function getAuthEventSerializer(): Serializer<AuthEventArgs, AuthEvent> {
  return struct<AuthEvent>(
    [
      ['multisig', publicKeySerializer()],
      ['programId', publicKeySerializer()],
    ],
    { description: 'AuthEvent' }
  ) as Serializer<AuthEventArgs, AuthEvent>;
}
