/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  publicKey as publicKeySerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';

export type TransactionCancelled = {
  multisig: PublicKey;
  transaction: PublicKey;
  programId: PublicKey;
};

export type TransactionCancelledArgs = TransactionCancelled;

export function getTransactionCancelledSerializer(): Serializer<
  TransactionCancelledArgs,
  TransactionCancelled
> {
  return struct<TransactionCancelled>(
    [
      ['multisig', publicKeySerializer()],
      ['transaction', publicKeySerializer()],
      ['programId', publicKeySerializer()],
    ],
    { description: 'TransactionCancelled' }
  ) as Serializer<TransactionCancelledArgs, TransactionCancelled>;
}
