/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  bool,
  bytes,
  publicKey as publicKeySerializer,
  struct,
  u32,
} from '@metaplex-foundation/umi/serializers';
import {
  TransactionAccount,
  TransactionAccountArgs,
  getTransactionAccountSerializer,
} from '.';

export type TransactionEdited = {
  multisig: PublicKey;
  transaction: PublicKey;
  programId: PublicKey;
  accounts: Array<TransactionAccount>;
  data: Uint8Array;
  signers: Array<boolean>;
};

export type TransactionEditedArgs = {
  multisig: PublicKey;
  transaction: PublicKey;
  programId: PublicKey;
  accounts: Array<TransactionAccountArgs>;
  data: Uint8Array;
  signers: Array<boolean>;
};

export function getTransactionEditedSerializer(): Serializer<
  TransactionEditedArgs,
  TransactionEdited
> {
  return struct<TransactionEdited>(
    [
      ['multisig', publicKeySerializer()],
      ['transaction', publicKeySerializer()],
      ['programId', publicKeySerializer()],
      ['accounts', array(getTransactionAccountSerializer())],
      ['data', bytes({ size: u32() })],
      ['signers', array(bool())],
    ],
    { description: 'TransactionEdited' }
  ) as Serializer<TransactionEditedArgs, TransactionEdited>;
}
