/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  publicKey as publicKeySerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';

export type TransactionApproved = {
  multisig: PublicKey;
  transaction: PublicKey;
  programId: PublicKey;
  approver: PublicKey;
};

export type TransactionApprovedArgs = TransactionApproved;

export function getTransactionApprovedSerializer(): Serializer<
  TransactionApprovedArgs,
  TransactionApproved
> {
  return struct<TransactionApproved>(
    [
      ['multisig', publicKeySerializer()],
      ['transaction', publicKeySerializer()],
      ['programId', publicKeySerializer()],
      ['approver', publicKeySerializer()],
    ],
    { description: 'TransactionApproved' }
  ) as Serializer<TransactionApprovedArgs, TransactionApproved>;
}
