name: Multisig CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Solana Environment
        uses: DhruvWebDev/solana-setup-action@v0.0.4
        with:
          node-version: '20'
          solana-cli-version: '1.18.26'
          anchor-version: '0.31.1'

      - name: Run x-ray analysis
        run: |
          docker run --rm \
            --volume "${{ github.workspace }}/multisig:/project" \
            ghcr.io/sec3-product/x-ray:latest \
            /project
            
      - name: Verify Solana CLI version
        run: solana --version

      - name: solana config
        run: |
          solana config get
          solana config set -u l 
          solana-keygen grind --starts-with msi:10 --no-outfile --format text
          solana address 
          solana airdrop 100
          solana-test-validator --reset --quiet &
          sleep 15
          solana balance 

      - name: Verify Anchor CLI version
        run: anchor --version

      - name: Anchor Build
        run: anchor build
        working-directory: ./multisig

      - name: Install npm packages
        run: npm install
        working-directory: ./multisig

      - name: Anchor Test
        run: anchor test
        working-directory: ./multisig
  
      # Optional: if x-ray supports outputting SARIF
      # - name: Upload SARIF report
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: multisig/output.sarif
