name: Multisig CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-the-program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Solana Environment
        uses: DhruvWebDev/solana-setup-action@v0.0.1
        with:
          node-version: '20'
          solana-cli-version: '1.18.26'
          anchor-version: '0.30.1'
          pnpm-package-manager: '8.15.5'
          yarn-package-manager: '1.22.19'

      - name: Verify Solana CLI version
        run: solana --version

      - name: solana config
        run: |
          solana config get
          solana config set --url devnet
          solana-keygen new
          solana address 
          solana airdrop 1 
          solana balance 

      - name: change dir
        run: |
         ls
         cd ./multisig
         ls
      
      - name: Verify Anchor CLI version
        run: anchor --version

      - name: Install project dependencies
        run: npm install

      - name: Anchor Build
        run: anchor build
