name: Multisig CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-test-program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Solana Environment
        uses: DhruvWebDev/solana-setup-action@v0.1.7
        with:
          node-version: '20'
          solana-cli-version: '1.18.26'
          anchor-version: 'v0.31.1'
          solana-network-url: 'http://localhost:8899'
          solana-airdrop-amount: '100'
          solana-wallet-setup: true
          build-script: 'anchor build'
          test-script: 'anchor test'
          deploy-script: 'anchor deploy --skip-local-validator --skip-build'
          x-ray-enabled: true
          working-directory: './multisig'
